In [14]:
import cv2
import os
import pandas as pd

# Function to preprocess image
def preprocess_image(image_path, target_size=(30, 30)):
    # Read the image
    img = cv2.imread(image_path)
    # Resize the image
    img = cv2.resize(img, target_size)
    # Convert image to grayscale
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Normalize the image
    img_normalized = img_gray / 255.0
    return img_normalized

# Define the directory containing the images
directory = "./datasets/dogs-vs-cats/train"

# Initialize lists to store data
data = []
labels = []
# Loop through the files in the directory
for filename in os.listdir(directory):
    if filename.startswith("dog"):
        label = 0  # Dog label
    elif filename.startswith("cat"):
        label = 1  # Cat label
    else:
        continue  # Skip files that don't start with "dog" or "cat"

    # Preprocess the image
    image_path = os.path.join(directory, filename)
    processed_image = preprocess_image(image_path)

    # Flatten the image and add to data list
    data.append(processed_image.flatten())
    labels.append(label)


# Convert lists to DataFrame
df = pd.DataFrame(data)
df["label"] = labels
df.to_csv("train.csv",index=False)

In [19]:
import pandas as pd
df=pd.read_csv("train.csv",index_col='Unnamed: 0')
df.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,891,892,893,894,895,896,897,898,899,label
0,0,0.741176,0.725490,0.635294,0.549020,0.250980,0.603922,0.192157,0.258824,0.592157,...,0.509804,0.447059,0.505882,0.501961,0.501961,0.529412,0.505882,0.498039,0.580392,1
1,1,0.164706,0.180392,0.168627,0.184314,0.172549,0.862745,0.188235,0.176471,0.176471,...,0.164706,0.070588,0.207843,0.160784,0.117647,0.156863,0.082353,0.301961,0.149020,0
2,2,0.007843,0.047059,0.066667,0.074510,0.035294,0.058824,0.070588,0.082353,0.109804,...,0.207843,0.149020,0.094118,0.505882,0.462745,0.376471,0.309804,0.231373,0.239216,1
3,3,0.098039,0.196078,0.317647,0.286275,0.298039,0.286275,0.305882,0.321569,0.274510,...,0.568627,0.576471,0.501961,0.698039,0.517647,0.745098,0.815686,0.607843,0.674510,0
4,4,0.309804,0.427451,0.250980,0.580392,0.396078,0.615686,0.509804,0.435294,0.419608,...,0.741176,0.537255,0.600000,0.305882,0.501961,0.866667,0.800000,0.745098,0.788235,0

In [17]:
import cv2
import os
import pandas as pd

# Function to preprocess image
def preprocess_image(image_path, target_size=(30, 30)):
    # Read the image
    img = cv2.imread(image_path)
    # Convert image to grayscale
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Resize the image
    img_resized = cv2.resize(img_gray, target_size)
    # Normalize the image
    img_normalized = img_resized / 255.0
    return img_normalized

# Define the directory containing the images
image_directory = "./datasets/dogs-vs-cats/test1"

# Initialize lists to store data
Data= []
Base=[]
# Loop through the files in the directory
for filename in os.listdir(image_directory):
    # Preprocess the image
    base, extension = os.path.splitext(filename)
    image_path = os.path.join(image_directory, filename)
    processed_image = preprocess_image(image_path)

    # Add the file name to the data
    Data.append(processed_image.flatten())
    Base.append(base)

# Convert list to DataFrame
df_test = pd.DataFrame(Data)
df_test["id"] = Base
df_test = df_test.sort_values(by='id').set_index('id')
# Read the labels CSV file
df_labels= pd.read_csv("./datasets/dogs-vs-cats/sampleSubmission.csv")

# Merge the labels with the test DataFrame based on the image ID
df_test['label']=df_labels['label'].values
# Save the test DataFrame to CSV file
df_test.to_csv("test.csv", index=False)

In [1]:
import pandas as pd
df=pd.read_csv("test.csv")
df.head()

,0,1,2,3,4,5,6,7,8,9,...,891,892,893,894,895,896,897,898,899,label
0,0.254902,0.243137,0.239216,0.262745,0.200000,0.239216,0.243137,0.235294,0.184314,0.105882,...,0.619608,0.819608,0.494118,0.658824,0.521569,0.415686,0.827451,0.509804,0.572549,0
1,0.035294,0.019608,0.231373,0.137255,0.113725,0.062745,0.031373,0.070588,0.078431,0.074510,...,0.478431,0.525490,0.474510,0.490196,0.474510,0.450980,0.333333,0.274510,0.262745,0
2,0.011765,0.007843,0.019608,0.031373,0.027451,0.027451,0.047059,0.258824,0.098039,0.188235,...,0.784314,0.996078,0.992157,0.945098,0.921569,0.960784,0.980392,0.996078,0.964706,0
3,0.670588,0.784314,0.792157,0.639216,0.725490,0.678431,0.749020,0.749020,0.737255,0.635294,...,0.803922,0.850980,0.898039,0.603922,0.423529,0.643137,0.505882,0.796078,0.596078,0
4,0.701961,0.796078,0.709804,0.756863,0.674510,0.713725,0.737255,0.745098,0.792157,0.874510,...,0.168627,0.482353,0.800000,0.611765,0.909804,0.749020,0.486275,0.725490,0.603922,0

In [3]:
x=df.drop("label",axis=1).values
y=df["label"].values

In [7]:
x.shape

(12500, 900)

In [31]:
df_train=pd.read_csv("train.csv",index_col="Unnamed: 0")
x=df_train.drop("label",axis=1).values
y=df_train["label"].values

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Train KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

# Predict labels for test set
y_pred = knn.predict(x_test)

# Evaluate performance
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.38      0.46      2482
           1       0.54      0.73      0.62      2518

    accuracy                           0.56      5000
   macro avg       0.56      0.56      0.54      5000
weighted avg       0.56      0.56      0.54      5000

In [35]:
from sklearn.model_selection import cross_val_score, KFold
import numpy as np


# Perform 10-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Define the scoring metrics
scoring = ['accuracy', 'precision', 'recall', 'f1']

# Store the scores for each metric
scores = {metric: cross_val_score(knn, x, y, cv=kf, scoring=metric) for metric in scoring}

# Compute average and standard deviation for each metric
avg_scores = {metric: np.mean(scores[metric]) for metric in scoring}
std_scores = {metric: np.std(scores[metric]) for metric in scoring}

# Print results
for metric in scoring:
    print("Average {}: {:.4f}".format(metric, avg_scores[metric]))
    print("{} Standard Deviation: {:.4f}".format(metric, std_scores[metric]))

Average accuracy: 0.5616
accuracy Standard Deviation: 0.0070
Average precision: 0.5457
precision Standard Deviation: 0.0080
Average recall: 0.7360
recall Standard Deviation: 0.0086
Average f1: 0.6267
f1 Standard Deviation: 0.0072